#!/bin/sh

while read file
do
	case "$1" in
		"C-d")
			mv "$file" ~/.trash ;;
		"C-c")
			echo -n "$file" | xclip -selection clipboard ;;
		"C-w")
			nitrogen --save --set-zoom-fill "$file" ;;
		"C-m")
			mv "$file" ~/Desktop/img/relic ;;
	esac
done
